routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index')->name('home');

Auth::routes();
Route::group(['middleware' => ['auth']], function () {
    Route::get('/profile', 'ProfileController@index')->name('profile');

    // Exchange
    Route::resource('exchange', 'ExchangeController');
    Route::resource('account', 'AccountController');
    // Send Mail
    Route::get('test', 'TradeController@update');
    /* Route::group(['prefix' => 'account'], function () {
        Route::get('create', 'AccountController@new')->name('account.create');
        Route::post('/', 'AccountController@store')->name('account.store');
        Route::get('{id}', 'AccountController@new')->name('account.show');
        Route::put('{id}', 'AccountController@update')->name('account.update');
        Route::delete('{id}', 'AccountController@new')->name('account.destroy');
        Route::fallback('AccountController@fallback');
    }); */
});

app/Models/Exchange.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Exchange extends Model
{
    protected $fillable = [
        'name',
    ];

    public static function createExchange(string $exchange_name, array $options)
    {
        $exchange_class = '\ccxt\\' . $exchange_name;
        if (class_exists($exchange_class)) {
            return new $exchange_class($options);
        }
    }

    public function initExchange()
    {
        $exchange_ccxt = self::createExchange($this->name, []);
        echo "Getting exchange's pairs for $this->name" . "\n";
        foreach ($exchange_ccxt->load_markets() as $pair) {
            $name = Currency::firstOrCreate([
                'name' => $pair['base']
            ]);
            $base = Currency::firstOrCreate([
                'name' => $pair['quote']
            ]);
            Pair::firstOrCreate([
                'currency_name_id' => $name->id,
                'currency_base_id' => $base->id,
                'exchange_id' => $this->id,
            ]);
        }
    }

    public static function getBalances()
    {
        $accounts = DB::table('accounts')->orderBy('id')->where('auto_refresh', '1')->get();
        $this->line('Syncing balances...');
        $bar = $this->output->createProgressBar(count($accounts));

        $bar->start();

        foreach ($accounts as $account) {
            $this->performTask($account);

            $bar->advance();
        }

        $bar->finish();
    }

    function pairs()
    {
        return $this->hasMany('App\Models\Pair');
    }
}

app/Http/Controllers/ExchangeController.php
<?php

namespace App\Http\Controllers;

use App\Exchange;
use Illuminate\Http\Request;
use App\Form;

class ExchangeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('exchange/index-exchange', ['exchanges' => Exchange::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('exchange/create-exchange');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|unique:exchanges|max:50',
        ]);

        Exchange::create($validatedData);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Exchange  $exchange
     * @return \Illuminate\Http\Response
     */
    public function show(Exchange $exchange)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Exchange  $exchange
     * @return \Illuminate\Http\Response
     */
    public function edit(Exchange $exchange)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Exchange  $exchange
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Exchange $exchange)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Exchange  $exchange
     * @return \Illuminate\Http\Response
     */
    public function destroy(Exchange $exchange)
    {
        //
    }
}

resources/views/exchange/create-exchange.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-header">
            {{ __('Create an exchange') }}
        </div>
        @if ($errors->any())
            <div class="alert alert-danger">
                    @foreach ($errors->all() as $error)
                    <p>{{ $error }}</p>
                    @endforeach
            </div><br />
        @endif
        <div class="card-body">
        <form method="post" action="{{ route('exchange.store') }}">
          <div class="form-group">
              @csrf
              <label for="name">{{ __('Exchange Name') }}</label>
              <input type="text" class="form-control" name="name"/>
          </div>
          <button type="submit" class="btn btn-primary">{{ __('Add Exchange') }}</button>
        </form>
        </div>
    </div>
</div>
@endsection

resources/views/exchange/index-exchange.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="panel panel-primary">
        <div class="panel-heading">
            {{ __('Exchanges') }}
        </div>
        @foreach ($exchanges as $exchange)
            <p>{{$exchange->name}} ({{count($exchange->pairs)}})</p>
        @endforeach
    </div>
</div>
@endsection